In [183]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.preprocessing import MinMaxScaler
from sklearn.inspection import permutation_importance
import pandas as pd;
import numpy as np
import matplotlib.pyplot as plt

In [184]:
df=pd.read_csv('./train.csv')

In [185]:
df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,label
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [186]:
df.describe()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,label
count,2000.000000,2000.0000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,...,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1238.518500,0.4950,1.522250,0.509500,4.309500,0.521500,32.046500,0.501750,140.249000,4.520500,...,645.108000,1251.515500,2124.213000,12.306500,5.767000,11.011000,0.761500,0.503000,0.507000,1.500000
std,439.418206,0.5001,0.816004,0.500035,4.341444,0.499662,18.145715,0.288416,35.399655,2.287837,...,443.780811,432.199447,1084.732044,4.213245,4.356398,5.463955,0.426273,0.500116,0.500076,1.118314
min,501.000000,0.0000,0.500000,0.000000,0.000000,0.000000,2.000000,0.100000,80.000000,1.000000,...,0.000000,500.000000,256.000000,5.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000
25%,851.750000,0.0000,0.700000,0.000000,1.000000,0.000000,16.000000,0.200000,109.000000,3.000000,...,282.750000,874.750000,1207.500000,9.000000,2.000000,6.000000,1.000000,0.000000,0.000000,0.750000
50%,1226.000000,0.0000,1.500000,1.000000,3.000000,1.000000,32.000000,0.500000,141.000000,4.000000,...,564.000000,1247.000000,2146.500000,12.000000,5.000000,11.000000,1.000000,1.000000,1.000000,1.500000
75%,1615.250000,1.0000,2.200000,1.000000,7.000000,1.000000,48.000000,0.800000,170.000000,7.000000,...,947.250000,1633.000000,3064.500000,16.000000,9.000000,16.000000,1.000000,1.000000,1.000000,2.250000
max,1998.000000,1.0000,3.000000,1.000000,19.000000,1.000000,64.000000,1.000000,200.000000,8.000000,...,1960.000000,1998.000000,3998.000000,19.000000,18.000000,20.000000,1.000000,1.000000,1.000000,3.000000

In [187]:
df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'label'],
      dtype='object')

In [188]:
scalers=[]

scale_cols=['battery_power',
'clock_speed',
'fc',
'int_memory',
'm_dep',
'mobile_wt',
'pc',
'px_height',
'px_width',
'ram',
'sc_h',
'sc_w',
'talk_time',]
for i in range(len(scale_cols)):
    m=MinMaxScaler()
    df[scale_cols[i]]=m.fit_transform(df[scale_cols[i]].values.reshape(-1,1))

In [189]:
df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,label
0,0.227789,0,0.68,0,0.052632,0,0.080645,0.555556,0.900000,2,...,0.010204,0.170895,0.612774,0.285714,0.388889,0.944444,0,0,1,1
1,0.347361,1,0.00,1,0.000000,1,0.822581,0.666667,0.466667,3,...,0.461735,0.993324,0.634687,0.857143,0.166667,0.277778,1,1,0,2
2,0.041416,1,0.00,1,0.105263,1,0.629032,0.888889,0.541667,5,...,0.644388,0.811749,0.627205,0.428571,0.111111,0.388889,1,1,0,2
3,0.076152,1,0.80,0,0.000000,0,0.129032,0.777778,0.425000,6,...,0.620408,0.858478,0.671566,0.785714,0.444444,0.500000,1,0,0,2
4,0.881764,1,0.28,0,0.684211,1,0.677419,0.555556,0.508333,2,...,0.616327,0.475300,0.308658,0.214286,0.111111,0.722222,1,1,0,1

In [190]:
# df.drop(['blue','dual_sim','four_g','three_g','touch_screen','wifi'],axis=1,inplace=True)
df.drop(['m_dep',
'pc',
'dual_sim',
'wifi',
'sc_w',
 'blue',
        'three_g',
'n_cores',
'four_g',
'fc',
'int_memory',
        

        
        ],axis=1,inplace=True)

In [191]:
df.head()

,battery_power,clock_speed,mobile_wt,px_height,px_width,ram,sc_h,talk_time,touch_screen,label
0,0.227789,0.68,0.900000,0.010204,0.170895,0.612774,0.285714,0.944444,0,1
1,0.347361,0.00,0.466667,0.461735,0.993324,0.634687,0.857143,0.277778,1,2
2,0.041416,0.00,0.541667,0.644388,0.811749,0.627205,0.428571,0.388889,1,2
3,0.076152,0.80,0.425000,0.620408,0.858478,0.671566,0.785714,0.500000,0,2
4,0.881764,0.28,0.508333,0.616327,0.475300,0.308658,0.214286,0.722222,1,1

In [192]:
X_train,X_test,y_train,y_test=train_test_split(df.drop('label',axis=1),df['label'],test_size=0.33,shuffle=True,)

In [193]:
model=RandomForestClassifier(n_estimators=100)

In [194]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [195]:
y_pred=model.predict(X_test)

In [196]:
(np.sum(y_pred==y_test)/len(y_pred))*100

90.30303030303031

In [203]:
# import eli5
# from eli5.sklearn import PermutationImportance

# perm = PermutationImportance(model, random_state=1).fit(X_test, y_test)
# eli5.show_weights(perm, feature_names = X_test.columns.tolist())

In [199]:
from sklearn.svm import SVC
svc = SVC(kernel = 'linear',random_state = 0)
svc.fit(X_train,y_train)

SVC(kernel='linear', random_state=0)

In [200]:
y_pred2=svc.predict(X_test)

In [202]:
(np.sum(y_pred2==y_test)/len(y_pred))*100

95.60606060606061

In [205]:
print(confusion_matrix(y_test,y_pred))

[[158   7   0   0]
 [  7 141  15   0]
 [  0  15 140   8]
 [  0   0  12 157]]

In [206]:
print(confusion_matrix(y_test,y_pred2))

[[162   3   0   0]
 [  4 156   3   0]
 [  0   8 150   5]
 [  0   0   6 163]]

In [207]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96       165
           1       0.87      0.87      0.87       163
           2       0.84      0.86      0.85       163
           3       0.95      0.93      0.94       169

    accuracy                           0.90       660
   macro avg       0.90      0.90      0.90       660
weighted avg       0.90      0.90      0.90       660

In [208]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       165
           1       0.93      0.96      0.95       163
           2       0.94      0.92      0.93       163
           3       0.97      0.96      0.97       169

    accuracy                           0.96       660
   macro avg       0.96      0.96      0.96       660
weighted avg       0.96      0.96      0.96       660